const { invoke } = window.__TAURI__.core;
const { listen } = window.__TAURI__.event;

window.electronAPI = {
  takeScreenshot: () => invoke('take_screenshot'),
  startSpeechRecognition: () => invoke('start_speech_recognition'),
  stopSpeechRecognition: () => invoke('stop_speech_recognition'),
  getSpeechAvailability: () => invoke('get_speech_availability'),
  showAllWindows: () => invoke('show_all_windows'),
  hideAllWindows: () => invoke('hide_all_windows'),
  enableWindowInteraction: () => invoke('enable_window_interaction'),
  disableWindowInteraction: () => invoke('disable_window_interaction'),
  switchToChat: () => invoke('switch_to_chat'),
  switchToSkills: () => invoke('switch_to_skills'),
  resizeWindow: (width, height) => invoke('resize_window', { width, height }),
  moveWindow: (deltaX, deltaY) => invoke('move_window', { deltaX, deltaY }),
  getSessionHistory: () => invoke('get_session_history'),
  clearSessionMemory: () => invoke('clear_session_memory'),
  sendChatMessage: (text) => invoke('send_chat_message', { text }),
  getSettings: () => invoke('get_settings'),
  showSettings: () => invoke('show_settings'),
  saveSettings: (settings) => invoke('save_settings', { settings }),
  updateAppIcon: (iconKey) => invoke('update_app_icon', { iconKey }),
  updateActiveSkill: (skill) => invoke('update_active_skill', { skill }),
  restartAppForStealth: () => invoke('restart_app_for_stealth'),
  closeWindow: () => invoke('close_window'),
  toggleAnswerHold: () => invoke('toggle_answer_hold'),
  copyToClipboard: (text) => invoke('copy_to_clipboard', { text }),
  sendAudioChunk: (chunk) => invoke('send_audio_chunk', { chunk: Array.from(new Uint8Array(chunk)) }),
  getDesktopAudioSource: () => invoke('get_desktop_audio_source'),
  getSkillPrompt: (skill) => invoke('get_skill_prompt', { skill }),
  getGeminiStatus: () => invoke('get_gemini_status'),
  testGeminiConnection: () => invoke('test_gemini_connection'),
  notifyMainWindowReady: () => invoke('notify_main_window_ready'),
  notifyLlmWindowReady: () => invoke('notify_llm_window_ready'),
  notifyLiveAnswerWindowReady: () => invoke('notify_live_answer_window_ready'),
  getWindowStats: () => invoke('get_window_stats'),
  quit: () => invoke('quit_app'),
  
    onInteractionModeChanged: (callback) => listen('interaction-mode-changed', (e) => callback(e, e.payload)),
  onRecordingStarted: (callback) => listen('recording-started', (e) => callback(e, e.payload)),
  onRecordingStopped: (callback) => listen('recording-stopped', (e) => callback(e, e.payload)),
  onCodingLanguageChanged: (callback) => listen('coding-language-changed', (e) => callback(e, e.payload)),
  onMainWindowShown: (callback) => listen('main-window-shown', (e) => callback(e, e.payload)),
  onTranscriptionReceived: (callback) => listen('transcription-received', (e) => callback(e, e.payload)),
  onRestartSpeechRecognition: (callback) => listen('restart-speech-recognition', (e) => callback(e, e.payload)),
  onInterimTranscription: (callback) => listen('interim-transcription', (e) => callback(e, e.payload)),
  onSpeechStatus: (callback) => listen('speech-status', (e) => callback(e, e.payload)),
  onSpeechError: (callback) => listen('speech-error', (e) => callback(e, e.payload)),
  onSpeechAvailability: (callback) => listen('speech-availability', (e) => callback(e, e.payload)),
  onSessionCleared: (callback) => listen('session-cleared', (e) => callback(e)),
    onOcrCompleted: (callback) => listen('ocr-completed', (e) => callback(e, e.payload)),
  onOcrError: (callback) => listen('ocr-error', (e) => callback(e, e.payload)),
  onLlmError: (callback) => listen('llm-error', (e) => callback(e, e.payload)),
  onTranscriptionLlmResponse: (callback) => listen('transcription-llm-response', (e) => callback(e, e.payload)),
  onLlmResponse: (callback) => listen('llm-response', (e) => callback(e, e.payload)),
  onTranscriptionLlmResponseStart: (callback) => listen('transcription-llm-response-start', (e) => callback(e, e.payload)),
  onTranscriptionLlmResponseChunk: (callback) => listen('transcription-llm-response-chunk', (e) => callback(e, e.payload)),
  onShowLoading: (callback) => listen('show-loading', (e) => callback(e, e.payload)),
  onDisplayLlmResponse: (callback) => listen('display-llm-response', (e) => callback(e, e.payload)),
  onSkillChanged: (callback) => listen('skill-changed', (e) => callback(e, e.payload)),
  onAnswerHoldChanged: (callback) => listen('answer-hold-changed', (e) => callback(e, e.payload)),
  arrangeWindows: () => invoke('arrange_windows'),
  hideLiveAnswerWindow: () => invoke('hide_live_answer_window'),
  
  receive: (channel, callback) => listen(channel, (e) => callback(e, e.payload)),
  removeAllListeners: (channel) => console.log('Tauri wrapper: removeAllListeners ignored for', channel)
};

window.api = {
  send: (channel, data) => invoke('legacy_send', { channel, data }),
  receive: (channel, callback) => listen(channel, (e) => callback(e, e.payload))
};
